### PR TITLE
Merge 'v13.4.0' into exodus-fork 

### PR DESCRIPTION
**Pull request by akinncar**
# Summary
- Merge v13.4.0
- Update package.json and Podfile version to `13.4.0-exodus.0`
- add `mask` and `offset` to `propWhitelist`

# Test Plan
Tested these SVGs in example app
```js
xml =
  '<svg width="40" height="40" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient x1="0%" y1="21.958%" x2="100%" y2="79.18%" id="a"><stop stop-color="#29CCC4" offset="0%"/><stop stop-color="#167D82" offset="100%"/></linearGradient></defs><g fill-rule="nonzero" fill="none"><path d="M22 1.155l13.32 7.69a4 4 0 012 3.464v15.382a4 4 0 01-2 3.464L22 38.845a4 4 0 01-4 0l-13.32-7.69a4 4 0 01-2-3.464V12.309a4 4 0 012-3.464L18 1.155a4 4 0 014 0z" fill="url(#a)"/><g fill="#FFF"><path d="M24.31 19.61l-7.703 3.787 7.702 3.654v2.945l-11.22-5.32-.006-2.901 7.806-3.838-7.8-3.697v-2.945l11.22 5.32z"/><path opacity=".3" d="M13.09 11.295l2.965-1.203 11.22 5.32-2.966 1.203z"/><path opacity=".5" d="M24.31 19.61l2.965-1.203v-2.995l-2.966 1.203zM24.31 27.05v-5.887l2.965-1.363v8.993l-2.966 1.203z"/></g></g></svg>';

xmlLuna =
  '<svg width="40" height="40" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M16.983 11.523c1.811-.675 3.85-.676 5.695-.122 2.402.743 4.43 2.548 5.49 4.813.292.645.572 1.319.6 2.036-1.35-.78-2.83-1.284-4.314-1.745-2.373-.851-4.857-1.443-7.103-2.613-.523-.311-1.19-.63-1.332-1.279-.057-.56.539-.873.964-1.09zm-5.467 5.452c.524-1.417 1.384-2.732 2.552-3.707.297 2.432 1.336 4.782 3.053 6.55 2.06 2.13 4.992 3.438 7.976 3.388 1.184.037 2.343-.235 3.498-.456-1.137 4.091-5.64 6.806-9.81 6.153-2.519-.32-4.844-1.805-6.247-3.9-1.582-2.317-1.981-5.393-1.022-8.028z" fill="#fff"/><path d="M24.455 16.505c1.483.46 2.964.966 4.314 1.745l.091.048c.125.938.217 1.895.05 2.834-.68-.287-1.23-.79-1.805-1.235-1.108-.918-2.239-1.968-2.65-3.392z" fill="#fff" fill-opacity=".6"/></svg>';

xmlRNDR =
  '<svg width="40" height="40" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M22 1.155l13.32 7.69a4 4 0 012 3.464v15.382a4 4 0 01-2 3.464L22 38.845a4 4 0 01-4 0l-13.32-7.69a4 4 0 01-2-3.464V12.309a4 4 0 012-3.464L18 1.155a4 4 0 014 0z" fill="url(#paint0_linear_320_704)"/><path fill-rule="evenodd" clip-rule="evenodd" d="M20 11a9 9 0 11-7.143 3.525 1.482 1.482 0 11.46.35A8.422 8.422 0 1020 11.577V11zm4.341 9.106a4.235 4.235 0 11-8.47 0 4.235 4.235 0 018.47 0zm-10.376-5.615a.95.95 0 110-1.901.95.95 0 010 1.901z" fill="#fff"/><defs><linearGradient id="paint0_linear_320_704" x1="38" y1="37.5" x2=".537" y2="6.714" gradientUnits="userSpaceOnUse"><stop stop-color="#E62249"/><stop offset="1" stop-color="#FA3960"/></linearGradient></defs></svg>';

xmlGradient =
  '<svg width="40" height="40" fill="none" xmlns="http://www.w3.org/2000/svg"><mask id="a" style="mask-type:alpha" maskUnits="userSpaceOnUse" x="2" y="0" width="36" height="40"><path fill-rule="evenodd" clip-rule="evenodd" d="M22 1.153l13.32 7.69a4 4 0 012 3.464V27.69a4 4 0 01-2 3.464L22 38.843a4 4 0 01-4 0l-13.32-7.69a4 4 0 01-2-3.464V12.307a4 4 0 012-3.464L18 1.153a4 4 0 014 0z" fill="url(#paint0_linear_124_35022)"/></mask><g mask="url(#a)"><path fill="#F08" d="M-8-3h59v45H-8z"/><g filter="url(#filter0_f_124_35022)"><circle cx="29.5" cy="29.5" r="20.5" fill="#13ECAB"/></g><g filter="url(#filter1_f_124_35022)"><circle cx="13.5" cy="13.5" r="20.5" fill="#C200FB"/></g><g filter="url(#filter2_f_124_35022)"><circle cx="47.5" cy="6.5" r="27.5" fill="#13ECAB"/></g><path opacity=".2" fill="url(#paint1_linear_124_35022)" d="M2 0h5.2v5.2H2z"/><path opacity=".3" fill="url(#paint2_linear_124_35022)" d="M2 5.203h5.2v5.2H2z"/><path opacity=".2" fill="url(#paint3_linear_124_35022)" d="M7.203 5.203h5.2v5.2h-5.2z"/><path opacity=".1" fill="url(#paint4_linear_124_35022)" d="M12.398 5.203h5.2v5.2h-5.2z"/><path opacity=".1" fill="url(#paint5_linear_124_35022)" d="M7.203 10.398h5.2v5.2h-5.2z"/><path opacity=".1" fill="url(#paint6_linear_124_35022)" d="M17.602 0h5.2v5.2h-5.2z"/><path opacity=".3" fill="url(#paint7_linear_124_35022)" d="M2 10.398h5.2v5.2H2z"/><path opacity=".1" fill="url(#paint8_linear_124_35022)" d="M2 15.602h5.2v5.2H2z"/><path opacity=".05" fill="url(#paint9_linear_124_35022)" d="M2 20.797h5.2v5.2H2z"/><path opacity=".2" transform="rotate(-180 37.797 40)" fill="url(#paint10_linear_124_35022)" d="M37.797 40h5.2v5.2h-5.2z"/><path opacity=".3" transform="rotate(-180 37.797 34.797)" fill="url(#paint11_linear_124_35022)" d="M37.797 34.797h5.2v5.2h-5.2z"/><path opacity=".2" transform="rotate(-180 32.594 34.797)" fill="url(#paint12_linear_124_35022)" d="M32.594 34.797h5.2v5.2h-5.2z"/><path opacity=".1" transform="rotate(-180 27.398 34.797)" fill="url(#paint13_linear_124_35022)" d="M27.398 34.797h5.2v5.2h-5.2z"/><path opacity=".1" transform="rotate(-180 32.594 29.602)" fill="url(#paint14_linear_124_35022)" d="M32.594 29.602h5.2v5.2h-5.2z"/><path opacity=".1" transform="rotate(-180 22.195 40)" fill="url(#paint15_linear_124_35022)" d="M22.195 40h5.2v5.2h-5.2z"/><path opacity=".3" transform="rotate(-180 37.797 29.602)" fill="url(#paint16_linear_124_35022)" d="M37.797 29.602h5.2v5.2h-5.2z"/><path opacity=".1" transform="rotate(-180 37.797 24.398)" fill="url(#paint17_linear_124_35022)" d="M37.797 24.398h5.2v5.2h-5.2z"/><path opacity=".05" transform="rotate(-180 37.797 19.203)" fill="url(#paint18_linear_124_35022)" d="M37.797 19.203h5.2v5.2h-5.2z"/></g><defs><linearGradient id="paint0_linear_124_35022" x1="-11.559" y1="33.301" x2="33.203" y2="51.582" gradientUnits="userSpaceOnUse"><stop stop-color="#1A1A1A"/><stop offset="1"/></linearGradient><linearGradient id="paint1_linear_124_35022" x1="2" y1="0" x2="7.2" y2="5.2" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint2_linear_124_35022" x1="2" y1="5.203" x2="7.2" y2="10.403" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint3_linear_124_35022" x1="7.203" y1="5.203" x2="12.403" y2="10.403" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint4_linear_124_35022" x1="12.398" y1="5.203" x2="17.598" y2="10.403" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint5_linear_124_35022" x1="7.203" y1="10.398" x2="12.403" y2="15.598" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint6_linear_124_35022" x1="17.602" y1="0" x2="22.802" y2="5.2" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint7_linear_124_35022" x1="2" y1="10.398" x2="7.2" y2="15.598" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint8_linear_124_35022" x1="2" y1="15.602" x2="7.2" y2="20.802" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint9_linear_124_35022" x1="2" y1="20.797" x2="7.2" y2="25.997" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint10_linear_124_35022" x1="37.797" y1="40" x2="42.997" y2="45.2" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint11_linear_124_35022" x1="37.797" y1="34.797" x2="42.997" y2="39.997" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint12_linear_124_35022" x1="32.594" y1="34.797" x2="37.794" y2="39.997" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint13_linear_124_35022" x1="27.398" y1="34.797" x2="32.598" y2="39.997" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint14_linear_124_35022" x1="32.594" y1="29.602" x2="37.794" y2="34.802" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint15_linear_124_35022" x1="22.195" y1="40" x2="27.395" y2="45.2" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint16_linear_124_35022" x1="37.797" y1="29.602" x2="42.997" y2="34.802" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint17_linear_124_35022" x1="37.797" y1="24.398" x2="42.997" y2="29.598" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><linearGradient id="paint18_linear_124_35022" x1="37.797" y1="19.203" x2="42.997" y2="24.403" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity=".5"/></linearGradient><filter id="filter0_f_124_35022" x="-16" y="-16" width="91" height="91" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur stdDeviation="12.5" result="effect1_foregroundBlur_124_35022"/></filter><filter id="filter1_f_124_35022" x="-32" y="-32" width="91" height="91" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur stdDeviation="12.5" result="effect1_foregroundBlur_124_35022"/></filter><filter id="filter2_f_124_35022" x="-5" y="-46" width="105" height="105" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur stdDeviation="12.5" result="effect1_foregroundBlur_124_35022"/></filter></defs></svg>';

render() {
  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>SVG library for React Apps</Text>
      <View style={styles.contentContainer}>{this.getExamples()}</View>
      <SvgXml xml={this.xml} />
      <SvgXml xml={this.xmlRNDR} />
      <SvgXml style={{backgroundColor: '#000'}} xml={this.xmlLuna} />
      <SvgXml xml={this.xmlGradient} />
      <Modal
        transparent={false}
        animationType="fade"
        visible={this.state.modal}
        onRequestClose={this.hide}>
        {this.modalContent()}
      </Modal>
    </View>
  );
}
```

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added documentation in `README.md`
- [ ] I updated the typed files (typescript)
- [ ] I added a test for the API in the `__tests__` folder

### CODE REVIEW

**Comment by akinncar** [comment]
why do we have propWhitelist? noticed lot of logs with other props in example app
image

**Comment by andrejborstnik** [comment]
@akinncar didn't we say we would apply our changes on top of `master/main` & open a PR so we can review it? This has changes from master in it as well, so it is hard to see what our change is and what the remote change is.

Ultimately this is up to the security audit team though, @matias-la do you have a preference here?

**Comment by akinncar** [comment]
hmm, I understood the opposite, master > exodus-fork, so we can keep master up to date with open source repo, got it

changed base branch to master

**Comment by andrejborstnik** [comment]
> hmm, I understood the opposite, master > exodus-fork, so we can keep master up to date with open source repo, got it
> 
> changed base branch to master

I suggested:
1. update master with open-source master/main
2. open a PR to master so that we see our changes & review them
3. once PR approved close it and force-push the PR branch to exodus-fork to maintain separation of our changes

**Pull request closed without merging**
