### PR TITLE
feat: add mask and offset to propWhitelist

### PR DESCRIPTION
**Pull request by akinncar**
# Summary
- Add `mask` and `offset` to propWhitelist to allow SVGs with theses props
- format code according to rest of the project

This can be enough at list for now, to try to avoid update RNSVG library to v12.

## Test Plan
you can test if these SVGs renders correctly (offset prop):
```js
xml =
  '<svg width="40" height="40" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient x1="0%" y1="21.958%" x2="100%" y2="79.18%" id="a"><stop stop-color="#29CCC4" offset="0%"/><stop stop-color="#167D82" offset="100%"/></linearGradient></defs><g fill-rule="nonzero" fill="none"><path d="M22 1.155l13.32 7.69a4 4 0 012 3.464v15.382a4 4 0 01-2 3.464L22 38.845a4 4 0 01-4 0l-13.32-7.69a4 4 0 01-2-3.464V12.309a4 4 0 012-3.464L18 1.155a4 4 0 014 0z" fill="url(#a)"/><g fill="#FFF"><path d="M24.31 19.61l-7.703 3.787 7.702 3.654v2.945l-11.22-5.32-.006-2.901 7.806-3.838-7.8-3.697v-2.945l11.22 5.32z"/><path opacity=".3" d="M13.09 11.295l2.965-1.203 11.22 5.32-2.966 1.203z"/><path opacity=".5" d="M24.31 19.61l2.965-1.203v-2.995l-2.966 1.203zM24.31 27.05v-5.887l2.965-1.363v8.993l-2.966 1.203z"/></g></g></svg>';

xmlRNDR =
  '<svg width="40" height="40" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M22 1.155l13.32 7.69a4 4 0 012 3.464v15.382a4 4 0 01-2 3.464L22 38.845a4 4 0 01-4 0l-13.32-7.69a4 4 0 01-2-3.464V12.309a4 4 0 012-3.464L18 1.155a4 4 0 014 0z" fill="url(#paint0_linear_320_704)"/><path fill-rule="evenodd" clip-rule="evenodd" d="M20 11a9 9 0 11-7.143 3.525 1.482 1.482 0 11.46.35A8.422 8.422 0 1020 11.577V11zm4.341 9.106a4.235 4.235 0 11-8.47 0 4.235 4.235 0 018.47 0zm-10.376-5.615a.95.95 0 110-1.901.95.95 0 010 1.901z" fill="#fff"/><defs><linearGradient id="paint0_linear_320_704" x1="38" y1="37.5" x2=".537" y2="6.714" gradientUnits="userSpaceOnUse"><stop stop-color="#E62249"/><stop offset="1" stop-color="#FA3960"/></linearGradient></defs></svg>';
  
render() {
  return (
    <View style={styles.container}>
      <SvgXml xml={this.xml} />
      <SvgXml xml={this.xmlRNDR} />
    </View>
  );
}
```

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added documentation in `README.md`
- [ ] I updated the typed files (typescript)
- [ ] I added a test for the API in the `__tests__` folder

### CODE REVIEW

**Review by andrejborstnik — COMMENTED** [review]
@akinncar in the future can you format in a separate commit from adding the entries 🙏 . This will make it easier to review

**Review by andrejborstnik — APPROVED** [review]
utACK

@akinncar in the future can you format in a separate commit from adding the entries 🙏 . This will make it easier to review

**Review by matias-la — APPROVED** [review]

**Comment by matias-la** [comment]
@akinncar merged. Do we need anything else or should I proceed to release a new version?

**Comment by akinncar** [comment]
that's it, you can do the release @matias-la, thanks!

**Pull request merged**
